name: fastai
channels:
  - peterjc123
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - atomicwrites=1.1.5=py36_0
  - attrs=18.1.0=py_0
  - backcall=0.1.0=py_0
  - bcolz=1.2.1=py36_1
  - blas=1.1=openblas
  - bleach=2.1.3=py_0
  - bokeh=0.12.16=py36_0
  - bzip2=1.0.6=vc14_1
  - ca-certificates=2018.4.16=0
  - certifi=2018.4.16=py36_0
  - cffi=1.11.5=py36_0
  - click=6.7=py_1
  - cloudpickle=0.5.3=py_0
  - colorama=0.3.9=py36_0
  - cycler=0.10.0=py36_0
  - cymem=1.31.2=py36_vc14_0
  - cytoolz=0.8.2=py36_0
  - dask=0.17.5=py_0
  - dask-core=0.17.5=py_0
  - decorator=4.3.0=py_0
  - dill=0.2.7.1=py36_0
  - distributed=1.21.8=py36_0
  - entrypoints=0.2.3=py36_1
  - expat=2.2.5=vc14_0
  - freetype=2.8.1=vc14_0
  - hdf5=1.10.1=vc14_2
  - heapdict=1.0.0=py36_0
  - html5lib=1.0.1=py_0
  - icu=58.2=vc14_0
  - ipykernel=4.8.2=py36_0
  - ipython=6.4.0=py36_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.2.1=py36_1
  - jedi=0.12.0=py36_0
  - jinja2=2.10=py36_0
  - jpeg=9b=vc14_2
  - jsonschema=2.6.0=py36_1
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.3=py36_0
  - jupyter_console=5.2.0=py36_0
  - jupyter_contrib_core=0.3.3=py36_1
  - jupyter_contrib_nbextensions=0.5.0=py36_0
  - jupyter_core=4.4.0=py_0
  - jupyter_highlight_selected_word=0.2.0=py36_0
  - jupyter_latex_envs=1.4.4=py36_0
  - jupyter_nbextensions_configurator=0.4.0=py36_0
  - kiwisolver=1.0.1=py36_1
  - libflang=5.0.0=vc14_20180208
  - libiconv=1.15=vc14_0
  - libpng=1.6.34=vc14_0
  - libsodium=1.0.16=vc14_0
  - libtiff=4.0.9=vc14_0
  - libxml2=2.9.8=vc14_0
  - libxslt=1.1.32=vc14_0
  - llvm-meta=5.0.0=0
  - locket=0.2.0=py36_1
  - lxml=4.2.1=py36_0
  - markupsafe=1.0=py36_0
  - matplotlib=2.2.2=py36_1
  - mistune=0.8.3=py36_1
  - more-itertools=4.1.0=py_0
  - msgpack-numpy=0.4.1=py_0
  - msgpack-python=0.4.8=py36_0
  - murmurhash=0.28.0=py36_vc14_0
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py36_0
  - notebook=5.5.0=py36_0
  - numexpr=2.6.5=py36_0
  - numpy=1.14.3=py36_blas_openblas_200
  - olefile=0.45.1=py36_0
  - openblas=0.2.20=vc14_7
  - openmp=5.0.0=vc14_1
  - openssl=1.0.2o=vc14_0
  - packaging=17.1=py_0
  - pandas=0.23.0=py36_1
  - pandoc=2.2.1=hde52d81_0
  - pandocfilters=1.4.2=py36_0
  - parso=0.2.1=py_0
  - partd=0.3.8=py36_0
  - path.py=10.3.1=py36_0
  - patsy=0.5.0=py36_0
  - pcre=8.41=vc14_1
  - pexpect=4.5.0=py36_0
  - pickleshare=0.7.4=py36_0
  - pillow=5.1.0=py36_0
  - pip=9.0.3=py36_0
  - plac=0.9.6=py36_0
  - pluggy=0.6.0=py_0
  - preshed=1.0.0=py36_vc14_0
  - prompt_toolkit=1.0.15=py36_0
  - psutil=5.4.5=py36_0
  - py=1.5.3=py_0
  - pycparser=2.18=py36_0
  - pygments=2.2.0=py36_0
  - pyparsing=2.2.0=py36_0
  - pyqt=5.6.0=py36_5
  - pyreadline=2.1=py36_0
  - pytables=3.4.3=py36_8
  - pytest=3.6.0=py36_1
  - python=3.6.5=1
  - python-dateutil=2.7.3=py_0
  - pytz=2018.4=py_0
  - pywinpty=0.5.2=py36_0
  - pyyaml=3.12=py36_1
  - pyzmq=17.0.0=py36_4
  - qt=5.6.2=vc14_1
  - qtconsole=4.3.1=py36_0
  - regex=2017.11.09=py36_0
  - seaborn=0.8.1=py36_0
  - send2trash=1.5.0=py_0
  - setuptools=39.2.0=py36_0
  - simplegeneric=0.8.1=py36_0
  - sip=4.18=py36_1
  - six=1.11.0=py36_1
  - snappy=1.1.7=vc14_1
  - sortedcontainers=1.5.10=py36_0
  - spacy=2.0.11=py36_vc14_0
  - sqlite=3.22.0=vc14_0
  - statsmodels=0.9.0=py36_0
  - tblib=1.3.2=py36_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_0
  - testpath=0.3.1=py36_0
  - thinc=6.10.2=py36_vc14_0
  - tk=8.6.7=vc14_0
  - toolz=0.9.0=py_0
  - tornado=4.5.3=py36_0
  - tqdm=4.23.3=py_0
  - traitlets=4.3.2=py36_0
  - ujson=1.35=py36_0
  - vc=14=0
  - vs2015_runtime=14.0.25420=0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_0
  - wheel=0.31.0=py36_0
  - widgetsnbextension=3.2.1=py36_0
  - wincertstore=0.2=py36_0
  - winpty=0.4.3=vc14_2
  - wrapt=1.10.11=py36_0
  - xz=5.2.3=0
  - yaml=0.1.7=vc14_0
  - zeromq=4.2.5=vc14_1
  - zict=0.1.3=py_0
  - zlib=1.2.11=vc14_0
  - blosc=1.14.3=he51fdeb_0
  #- cudnn=6.0=0
  - icc_rt=2017.0.4=h97af966_0
  - intel-openmp=2018.0.0=8
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2018.0.2=1
  - msys2-conda-epoch=20160418=1
  - scipy=1.1.0=py36h672f292_0
  #- pytorch=0.3.1=py36_cuda90_cudnn7he774522_2
  - pytorch<0.4
  #- cuda90=1.0=0
  - pip:
    - beautifulsoup4==4.6.0
    - chardet==3.0.4
    - cliff==2.8.1
    - cmd2==0.8.5
    - configparser==3.5.0
    - cssselect==1.0.3
    - feather-format==0.4.0
    - graphviz==0.8.3
    - idna==2.6
    - isoweek==1.3.3
    - kaggle-cli==0.12.13
    - mechanicalsoup==0.8.0
    - mizani==0.4.6
    - networkx==2.1
    - opencv-python==3.4.1.15
    - palettable==3.1.1
    - pandas-summary==0.0.41
    - pbr==4.0.3
    - plotnine==0.3.0
    - prettytable==0.7.2
    - progressbar2==3.34.3
    - pyarrow==0.9.0
    - pyperclip==1.6.1
    - python-utils==2.3.0
    - pywavelets==0.5.2
    - requests==2.18.4
    - scikit-image==0.13.1
    - scikit-learn==0.19.1
    - sklearn-pandas==1.6.0
    - stevedore==1.28.0
    - tables==3.4.3
    - torch==0.3.1.post2
    - torchtext==0.2.3
    - torchvision==0.2.1
    - urllib3==1.22
prefix: C:\Anaconda3\envs\fastai

